import { Color } from '../types'
import { palette } from './palette'

export const color = {
  text: {
    system: {
      strong: palette.base['black'],
      subtle: palette.grey[800],
      subtler: palette.grey[500],
      inverse: palette.base['white'],
      staticWhite: palette.base['white'],
      brand: palette.primary[500],
      link: palette.primary[500],
      disabled: palette.grey[300],
      success: palette.green[500],
      successDark: palette.green[700],
      warning: palette.yellow[500],
      warningDark: palette.yellow[700],
      error: palette.red[500],
      errorDark: palette.red[700],
      observationStrong: palette.accentLime[400],
      speciesStrong: palette.accentSky[400],
    },
    gps: {
      accuracySuccess: palette.green[600],
      accuracyWarning: palette.yellow[600],
      accuracyError: palette.red[600],
    },
  },
  background: {
    system: {
      surfaceBase: palette.base['white'],
      surfaceRaised: palette.grey[50],
      surfaceLowered: palette.grey[100],
      disabled: palette.grey[300],
      surfacePopped: palette.base['black'],
      brand: palette.primary[500],
      success: palette.green[500],
      successSubtle: palette.green[200],
      warning: palette.yellow[500],
      warningSubtle: palette.yellow[200],
      error: palette.red[500],
      errorSubtle: palette.red[200],
      coverImage: palette.green[600],
      observationSubtle: palette.accentLime[50],
      observationStrong: palette.accentLime[400],
      speciesSubtle: palette.accentSky[50],
      speciesStrong: palette.accentSky[400],
      active: palette.primary[50],
      accented: palette.accentSky[400],
    },
    gps: {
      accuracySuccess: palette.green[200],
      accuracyWarning: palette.yellow[200],
      accuracyError: palette.red[200],
    },
  },
  icon: {
    system: {
      strong: palette.base['black'],
      subtle: palette.grey[800],
      subtler: palette.grey[500],
      staticWhite: palette.base['white'],
      brand: palette.primary[500],
      link: palette.primary[500],
      disabled: palette.grey[300],
      success: palette.green[500],
      warning: palette.yellow[500],
      error: palette.red[500],
      observationStrong: palette.accentLime[400],
      speciesStrong: palette.accentSky[400],
    },
    rarity: {
      unknown: palette.grey[400],
      common: palette.green[500],
      relativelyCommon: palette.accentCyan[400],
      rare: palette.yellow[500],
      veryRare: palette.red[500],
    },
    speciesStatus: {
      native: palette.green[500],
      incidentalMigrant: palette.green[500],
      insufficientData: palette.grey[400],
      other: palette.red[500],
      unknown: palette.grey[400],
    },
    validation: {
      unknown: palette.grey[700],
      accepted: palette.green[500],
      plausible: palette.primary[500],
      automatic: palette.grey[700],
      pending: palette.yellow[500],
      rejected: palette.red[500],
      cannotBeValidated: palette.grey[700],
    },
  },
  border: {
    system: {
      subtle: palette.grey[50],
      subtler: palette.grey[500],
      brand: palette.primary[500],
      disabled: palette.grey[300],
      success: palette.green[500],
      warning: palette.yellow[500],
      error: palette.red[500],
      inverse: palette.base['white'],
      speciesStrong: palette.accentSky[400],
      observationStrong: palette.accentLime[400],
      strong: palette.base['black'],
      base: palette.grey[300],
      focus: palette.primary[300],
      transect: palette.red[500],
      transectBorder: palette.base['white'],
      selected: palette.green[200],
    },
    status: {
      uploadable: palette.accentSky[400],
      error: palette.red[500],
    },
    syncStatus: {
      local: palette.accentSky[400],
    },
  },

  // Deprecated flat properties — kept for backward compatibility with consuming apps.
  // Use the semantic tokens above instead.
  white: palette.base['white'],
  black: palette.base['black'],
  grey800: palette.grey[800],
  grey500: palette.grey[500],
  grey300: palette.grey[300],
  grey50: palette.grey[50],
  grey100: palette.grey[100],
  primary500: palette.primary[500],
  primary300: palette.primary[300],
  primary50: palette.primary[50],
  success500: palette.green[500],
  success400: palette.green[400],
  success200: palette.green[200],
  success50: palette.green[50],
  success600: palette.green[600],
  success700: palette.green[700],
  warning500: palette.yellow[500],
  warning200: palette.yellow[200],
  warning700: palette.yellow[700],
  error500: palette.red[500],
  error200: palette.red[200],
  error700: palette.red[700],
  accentLime400: palette.accentLime[400],
  accentLime50: palette.accentLime[50],
  accentSky400: palette.accentSky[400],
  accentSky50: palette.accentSky[50],
} satisfies Color
