import { Color } from '../types'
import { palette } from './palette'

const paletteMode = palette.light

export const color = {
  text: {
    system: {
      strong: paletteMode.base['black'],
      subtle: paletteMode.grey[800],
      subtler: paletteMode.grey[500],
      inverse: paletteMode.base['white'],
      staticWhite: paletteMode.base['white'],
      brand: paletteMode.primary[500],
      link: paletteMode.primary[500],
      disabled: paletteMode.grey[300],
      success: paletteMode.success[500],
      successDark: paletteMode.success[700],
      warning: paletteMode.warning[500],
      warningDark: paletteMode.warning[700],
      error: paletteMode.error[500],
      errorDark: paletteMode.error[700],
      observationStrong: paletteMode.accentLime[400],
      speciesStrong: paletteMode.accentSky[400],
    },
    gps: {
      accuracySuccess: paletteMode.success[600],
      accuracyWarning: paletteMode.warning[600],
      accuracyError: paletteMode.error[600],
    },
  },
  background: {
    system: {
      surfaceBase: paletteMode.base['white'],
      surfaceRaised: paletteMode.grey[50],
      surfaceLowered: paletteMode.grey[100],
      disabled: paletteMode.grey[300],
      surfacePopped: paletteMode.base['black'],
      brand: paletteMode.primary[500],
      success: paletteMode.success[500],
      successSubtle: paletteMode.success[200],
      warning: paletteMode.warning[500],
      warningSubtle: paletteMode.warning[200],
      error: paletteMode.error[500],
      errorSubtle: paletteMode.error[200],
      coverImage: paletteMode.success[600],
      observationSubtle: paletteMode.accentLime[50],
      observationStrong: paletteMode.accentLime[400],
      speciesSubtle: paletteMode.accentSky[50],
      speciesStrong: paletteMode.accentSky[400],
      active: paletteMode.primary[50],
    },
    gps: {
      accuracySuccess: paletteMode.success[200],
      accuracyWarning: paletteMode.warning[200],
      accuracyError: paletteMode.error[200],
    },
  },
  icon: {
    system: {
      strong: paletteMode.base['black'],
      subtle: paletteMode.grey[800],
      subtler: paletteMode.grey[500],
      staticWhite: paletteMode.base['white'],
      brand: paletteMode.primary[500],
      link: paletteMode.primary[500],
      disabled: paletteMode.grey[300],
      success: paletteMode.success[500],
      warning: paletteMode.warning[500],
      error: paletteMode.error[500],
      observationStrong: paletteMode.accentLime[400],
      speciesStrong: paletteMode.accentSky[400],
    },
    rarity: {
      unknown: paletteMode.rarity['unknown'],
      common: paletteMode.rarity['common'],
      relativelyCommon: paletteMode.rarity['relativelyCommon'],
      rare: paletteMode.rarity['rare'],
      veryRare: paletteMode.rarity['veryRare'],
    },
    speciesStatus: {
      unknown: paletteMode.speciesStatus['unknown'],
      insufficientData: paletteMode.speciesStatus['insufficientData'],
      native: paletteMode.speciesStatus['native'],
      exoticEtc: paletteMode.speciesStatus['exoticEtc'],
    },
    validation: {
      unknown: paletteMode.validation['unknown'],
      accepted: paletteMode.validation['accepted'],
      plausible: paletteMode.validation['plausible'],
      automatic: paletteMode.validation['automatic'],
      pending: paletteMode.validation['pending'],
      rejected: paletteMode.validation['rejected'],
      cannotBeValidated: paletteMode.validation['cannotBeValidated'],
    },
  },
  border: {
    system: {
      subtle: paletteMode.grey[50],
      subtler: paletteMode.grey[500],
      brand: paletteMode.primary[500],
      disabled: paletteMode.grey[300],
      success: paletteMode.success[500],
      warning: paletteMode.warning[500],
      error: paletteMode.error[500],
      inverse: paletteMode.base['white'],
      speciesStrong: paletteMode.accentSky[400],
      observationStrong: paletteMode.accentLime[400],
      strong: paletteMode.base['black'],
      base: paletteMode.grey[300],
      focus: paletteMode.primary[300],
      transect: paletteMode.error[500],
      transectBorder: paletteMode.base['white'],
      selected: paletteMode.success[200],
    },
    status: {
      uploadable: paletteMode.accentSky[400],
      error: paletteMode.error[500],
    },
  },

  // Deprecated flat properties — kept for backward compatibility with consuming apps.
  // Use the semantic tokens above instead.
  white: paletteMode.base['white'],
  black: paletteMode.base['black'],
  grey800: paletteMode.grey[800],
  grey500: paletteMode.grey[500],
  grey300: paletteMode.grey[300],
  grey50: paletteMode.grey[50],
  grey100: paletteMode.grey[100],
  primary500: paletteMode.primary[500],
  primary300: paletteMode.primary[300],
  primary50: paletteMode.primary[50],
  success500: paletteMode.success[500],
  success400: paletteMode.success[400],
  success200: paletteMode.success[200],
  success50: paletteMode.success[50],
  success600: paletteMode.success[600],
  success700: paletteMode.success[700],
  warning500: paletteMode.warning[500],
  warning200: paletteMode.warning[200],
  warning700: paletteMode.warning[700],
  error500: paletteMode.error[500],
  error200: paletteMode.error[200],
  error700: paletteMode.error[700],
  accentLime400: paletteMode.accentLime[400],
  accentLime50: paletteMode.accentLime[50],
  accentSky400: paletteMode.accentSky[400],
  accentSky50: paletteMode.accentSky[50],
} satisfies Color
