name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: |
          yarn config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
          yarn
      - name: Run eslint
        run: yarn lint
      - name: Run tests with coverage
        run: yarn test --coverage --silent
