name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run lint
        run: yarn lint
      - name: Run tests with coverage
        run: yarn test --coverage --silent
