name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v7
      - name: Cache Yarn cache and node_modules
        uses: actions/cache@v6
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install modules
        run: yarn
      - name: Run lint
        run: yarn lint
      - name: Run tests with coverage
        run: yarn test --coverage --silent
